/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VksDashboardRouteImport } from './routes/vks.dashboard'
import { Route as ServicesWebServicesRouteImport } from './routes/services.web-services'
import { Route as ServicesWebRouteImport } from './routes/services.web'
import { Route as ServicesSocialSphereRouteImport } from './routes/services.social-sphere'
import { Route as ServicesMaintenanceSupportRouteImport } from './routes/services.maintenance-support'
import { Route as ServicesMaintenanceRouteImport } from './routes/services.maintenance'
import { Route as ServicesAppDevelopmentRouteImport } from './routes/services.app-development'
import { Route as ServicesAppRouteImport } from './routes/services.app'
import { Route as BlogsSlugRouteImport } from './routes/blogs_.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as VksDashboardIndexRouteImport } from './routes/vks.dashboard.index'
import { Route as VksDashboardSettingsRouteImport } from './routes/vks.dashboard.settings'
import { Route as VksDashboardJobsRouteImport } from './routes/vks.dashboard.jobs'
import { Route as VksDashboardChangePasswordRouteImport } from './routes/vks.dashboard.change-password'
import { Route as VksDashboardBlogsRouteImport } from './routes/vks.dashboard.blogs'
import { Route as VksDashboardApplicationsRouteImport } from './routes/vks.dashboard.applications'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VksDashboardRoute = VksDashboardRouteImport.update({
  id: '/vks/dashboard',
  path: '/vks/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebServicesRoute = ServicesWebServicesRouteImport.update({
  id: '/services/web-services',
  path: '/services/web-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebRoute = ServicesWebRouteImport.update({
  id: '/services/web',
  path: '/services/web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialSphereRoute = ServicesSocialSphereRouteImport.update({
  id: '/services/social-sphere',
  path: '/services/social-sphere',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaintenanceSupportRoute =
  ServicesMaintenanceSupportRouteImport.update({
    id: '/services/maintenance-support',
    path: '/services/maintenance-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMaintenanceRoute = ServicesMaintenanceRouteImport.update({
  id: '/services/maintenance',
  path: '/services/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAppDevelopmentRoute = ServicesAppDevelopmentRouteImport.update({
  id: '/services/app-development',
  path: '/services/app-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAppRoute = ServicesAppRouteImport.update({
  id: '/services/app',
  path: '/services/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs_/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VksDashboardIndexRoute = VksDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VksDashboardRoute,
} as any)
const VksDashboardSettingsRoute = VksDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VksDashboardRoute,
} as any)
const VksDashboardJobsRoute = VksDashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => VksDashboardRoute,
} as any)
const VksDashboardChangePasswordRoute =
  VksDashboardChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => VksDashboardRoute,
  } as any)
const VksDashboardBlogsRoute = VksDashboardBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => VksDashboardRoute,
} as any)
const VksDashboardApplicationsRoute =
  VksDashboardApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => VksDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/services/app': typeof ServicesAppRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/maintenance-support': typeof ServicesMaintenanceSupportRoute
  '/services/social-sphere': typeof ServicesSocialSphereRoute
  '/services/web': typeof ServicesWebRoute
  '/services/web-services': typeof ServicesWebServicesRoute
  '/vks/dashboard': typeof VksDashboardRouteWithChildren
  '/vks/dashboard/applications': typeof VksDashboardApplicationsRoute
  '/vks/dashboard/blogs': typeof VksDashboardBlogsRoute
  '/vks/dashboard/change-password': typeof VksDashboardChangePasswordRoute
  '/vks/dashboard/jobs': typeof VksDashboardJobsRoute
  '/vks/dashboard/settings': typeof VksDashboardSettingsRoute
  '/vks/dashboard/': typeof VksDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/services/app': typeof ServicesAppRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/maintenance-support': typeof ServicesMaintenanceSupportRoute
  '/services/social-sphere': typeof ServicesSocialSphereRoute
  '/services/web': typeof ServicesWebRoute
  '/services/web-services': typeof ServicesWebServicesRoute
  '/vks/dashboard/applications': typeof VksDashboardApplicationsRoute
  '/vks/dashboard/blogs': typeof VksDashboardBlogsRoute
  '/vks/dashboard/change-password': typeof VksDashboardChangePasswordRoute
  '/vks/dashboard/jobs': typeof VksDashboardJobsRoute
  '/vks/dashboard/settings': typeof VksDashboardSettingsRoute
  '/vks/dashboard': typeof VksDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/blogs_/$slug': typeof BlogsSlugRoute
  '/services/app': typeof ServicesAppRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/maintenance-support': typeof ServicesMaintenanceSupportRoute
  '/services/social-sphere': typeof ServicesSocialSphereRoute
  '/services/web': typeof ServicesWebRoute
  '/services/web-services': typeof ServicesWebServicesRoute
  '/vks/dashboard': typeof VksDashboardRouteWithChildren
  '/vks/dashboard/applications': typeof VksDashboardApplicationsRoute
  '/vks/dashboard/blogs': typeof VksDashboardBlogsRoute
  '/vks/dashboard/change-password': typeof VksDashboardChangePasswordRoute
  '/vks/dashboard/jobs': typeof VksDashboardJobsRoute
  '/vks/dashboard/settings': typeof VksDashboardSettingsRoute
  '/vks/dashboard/': typeof VksDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/blogs'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/terms-of-service'
    | '/admin/login'
    | '/blogs/$slug'
    | '/services/app'
    | '/services/app-development'
    | '/services/maintenance'
    | '/services/maintenance-support'
    | '/services/social-sphere'
    | '/services/web'
    | '/services/web-services'
    | '/vks/dashboard'
    | '/vks/dashboard/applications'
    | '/vks/dashboard/blogs'
    | '/vks/dashboard/change-password'
    | '/vks/dashboard/jobs'
    | '/vks/dashboard/settings'
    | '/vks/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/blogs'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/terms-of-service'
    | '/admin/login'
    | '/blogs/$slug'
    | '/services/app'
    | '/services/app-development'
    | '/services/maintenance'
    | '/services/maintenance-support'
    | '/services/social-sphere'
    | '/services/web'
    | '/services/web-services'
    | '/vks/dashboard/applications'
    | '/vks/dashboard/blogs'
    | '/vks/dashboard/change-password'
    | '/vks/dashboard/jobs'
    | '/vks/dashboard/settings'
    | '/vks/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/blogs'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/terms-of-service'
    | '/admin/login'
    | '/blogs_/$slug'
    | '/services/app'
    | '/services/app-development'
    | '/services/maintenance'
    | '/services/maintenance-support'
    | '/services/social-sphere'
    | '/services/web'
    | '/services/web-services'
    | '/vks/dashboard'
    | '/vks/dashboard/applications'
    | '/vks/dashboard/blogs'
    | '/vks/dashboard/change-password'
    | '/vks/dashboard/jobs'
    | '/vks/dashboard/settings'
    | '/vks/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  TermsRoute: typeof TermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  ServicesAppRoute: typeof ServicesAppRoute
  ServicesAppDevelopmentRoute: typeof ServicesAppDevelopmentRoute
  ServicesMaintenanceRoute: typeof ServicesMaintenanceRoute
  ServicesMaintenanceSupportRoute: typeof ServicesMaintenanceSupportRoute
  ServicesSocialSphereRoute: typeof ServicesSocialSphereRoute
  ServicesWebRoute: typeof ServicesWebRoute
  ServicesWebServicesRoute: typeof ServicesWebServicesRoute
  VksDashboardRoute: typeof VksDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vks/dashboard': {
      id: '/vks/dashboard'
      path: '/vks/dashboard'
      fullPath: '/vks/dashboard'
      preLoaderRoute: typeof VksDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-services': {
      id: '/services/web-services'
      path: '/services/web-services'
      fullPath: '/services/web-services'
      preLoaderRoute: typeof ServicesWebServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web': {
      id: '/services/web'
      path: '/services/web'
      fullPath: '/services/web'
      preLoaderRoute: typeof ServicesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-sphere': {
      id: '/services/social-sphere'
      path: '/services/social-sphere'
      fullPath: '/services/social-sphere'
      preLoaderRoute: typeof ServicesSocialSphereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maintenance-support': {
      id: '/services/maintenance-support'
      path: '/services/maintenance-support'
      fullPath: '/services/maintenance-support'
      preLoaderRoute: typeof ServicesMaintenanceSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maintenance': {
      id: '/services/maintenance'
      path: '/services/maintenance'
      fullPath: '/services/maintenance'
      preLoaderRoute: typeof ServicesMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/app-development': {
      id: '/services/app-development'
      path: '/services/app-development'
      fullPath: '/services/app-development'
      preLoaderRoute: typeof ServicesAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/app': {
      id: '/services/app'
      path: '/services/app'
      fullPath: '/services/app'
      preLoaderRoute: typeof ServicesAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs_/$slug': {
      id: '/blogs_/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vks/dashboard/': {
      id: '/vks/dashboard/'
      path: '/'
      fullPath: '/vks/dashboard/'
      preLoaderRoute: typeof VksDashboardIndexRouteImport
      parentRoute: typeof VksDashboardRoute
    }
    '/vks/dashboard/settings': {
      id: '/vks/dashboard/settings'
      path: '/settings'
      fullPath: '/vks/dashboard/settings'
      preLoaderRoute: typeof VksDashboardSettingsRouteImport
      parentRoute: typeof VksDashboardRoute
    }
    '/vks/dashboard/jobs': {
      id: '/vks/dashboard/jobs'
      path: '/jobs'
      fullPath: '/vks/dashboard/jobs'
      preLoaderRoute: typeof VksDashboardJobsRouteImport
      parentRoute: typeof VksDashboardRoute
    }
    '/vks/dashboard/change-password': {
      id: '/vks/dashboard/change-password'
      path: '/change-password'
      fullPath: '/vks/dashboard/change-password'
      preLoaderRoute: typeof VksDashboardChangePasswordRouteImport
      parentRoute: typeof VksDashboardRoute
    }
    '/vks/dashboard/blogs': {
      id: '/vks/dashboard/blogs'
      path: '/blogs'
      fullPath: '/vks/dashboard/blogs'
      preLoaderRoute: typeof VksDashboardBlogsRouteImport
      parentRoute: typeof VksDashboardRoute
    }
    '/vks/dashboard/applications': {
      id: '/vks/dashboard/applications'
      path: '/applications'
      fullPath: '/vks/dashboard/applications'
      preLoaderRoute: typeof VksDashboardApplicationsRouteImport
      parentRoute: typeof VksDashboardRoute
    }
  }
}

interface VksDashboardRouteChildren {
  VksDashboardApplicationsRoute: typeof VksDashboardApplicationsRoute
  VksDashboardBlogsRoute: typeof VksDashboardBlogsRoute
  VksDashboardChangePasswordRoute: typeof VksDashboardChangePasswordRoute
  VksDashboardJobsRoute: typeof VksDashboardJobsRoute
  VksDashboardSettingsRoute: typeof VksDashboardSettingsRoute
  VksDashboardIndexRoute: typeof VksDashboardIndexRoute
}

const VksDashboardRouteChildren: VksDashboardRouteChildren = {
  VksDashboardApplicationsRoute: VksDashboardApplicationsRoute,
  VksDashboardBlogsRoute: VksDashboardBlogsRoute,
  VksDashboardChangePasswordRoute: VksDashboardChangePasswordRoute,
  VksDashboardJobsRoute: VksDashboardJobsRoute,
  VksDashboardSettingsRoute: VksDashboardSettingsRoute,
  VksDashboardIndexRoute: VksDashboardIndexRoute,
}

const VksDashboardRouteWithChildren = VksDashboardRoute._addFileChildren(
  VksDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  TermsRoute: TermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  ServicesAppRoute: ServicesAppRoute,
  ServicesAppDevelopmentRoute: ServicesAppDevelopmentRoute,
  ServicesMaintenanceRoute: ServicesMaintenanceRoute,
  ServicesMaintenanceSupportRoute: ServicesMaintenanceSupportRoute,
  ServicesSocialSphereRoute: ServicesSocialSphereRoute,
  ServicesWebRoute: ServicesWebRoute,
  ServicesWebServicesRoute: ServicesWebServicesRoute,
  VksDashboardRoute: VksDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
